FlightSchedule/Models/AirlineViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace FlightSchedule.Models
{
    public class AirlineViewModel
    {
        [Required]  
        public int Id { get; set; }

        [Required]

        public string  NameEN { get; set; }
        [Required]

        public string NameAR { get; set; }
        [Required]

        public string IATA { get; set; }
        [Required]

        public string ICAO { get; set; }

        [Display(Name ="Email (Airline)")]
        [EmailAddress]
        public string AirlineEmail { get; set; }

        public string ?Images { get; set; }
        public string ?DisplayName { get; set; }
    }
}

FlightSchedule/Controllers/AirlineController.cs
using FlightSchedule.Enities;
using FlightSchedule.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing.Constraints;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;

namespace FlightSchedule.Controllers
{
    [Authorize]

    public class AirlineController : Controller
    {

        private readonly ApplicationDbContext.ApplicationDbContext _applicationDbContext;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public AirlineController(ApplicationDbContext.ApplicationDbContext applicationDbContext, IWebHostEnvironment webHostEnvironment)
        {
            _applicationDbContext = applicationDbContext;
            _webHostEnvironment = webHostEnvironment;
        }


        public static List<AirlineViewModel> Airlines = new List<AirlineViewModel>();
        [HttpGet]
        
        public IActionResult CreateAirline()
        {
            return View();
        }

//        private bool ValidateEmail(string  email)
//        {
//            bool isValid = true;

//            if (
//string.IsNullOrEmpty(email))
//            {

//                isValid = false; 
//            }


//            if (email.Length < 7)
//            {
//                isValid = false; 
//            }


//            if (!email.Contains('@'))
//            { 
//             isValid = false;
//            }



//           return isValid; 
        
//        }
        [HttpPost]
        public IActionResult CreateAirline(AirlineViewModel airline, IFormFile file)
        {
            airline.NameEN=  airline.NameEN.Trim(); 
            var anyRecordsWithSameEnName = _applicationDbContext.Airlines.Where(x => x.NameEN.ToLower() == airline.NameEN.ToLower()).Count();

            string errMsg=string.Empty;

            if (anyRecordsWithSameEnName > 0)
            {

                errMsg = "Name Already Exsist";

            }
            else
            {

                    FlightSchedule.Enities.Airline airlineObjectToInsert= new Enities.Airline();

                    airlineObjectToInsert.NameEN = airline.NameEN; 
                    airlineObjectToInsert.NameAR = airline.NameAR; 
                    airlineObjectToInsert.AirlineEmail = airline.AirlineEmail; 
                    airlineObjectToInsert.IATA = airline.IATA;
                    airlineObjectToInsert.ICAO = airline.ICAO;
                    _applicationDbContext.Airlines.Add(airlineObjectToInsert);
                    _applicationDbContext.SaveChanges();

                    string uniqueFileName = null; ;
                    if (file != null)
                    {
                        string fileExtension = Path.GetExtension(file.FileName);
                        string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                        uniqueFileName = airlineObjectToInsert.Id.ToString() + fileExtension;
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }
                    }
                    airline.Images = uniqueFileName;
                    airlineObjectToInsert.Images = airline.Images;
                    _applicationDbContext.Airlines.Update(airlineObjectToInsert);
                    _applicationDbContext.SaveChanges();

            }
            ViewBag.ErrMsg = errMsg; 
                return View(airline);
            }


        [HttpGet]
        public IActionResult Index(string? airlineName) //  Get  All Records 
        {

            //  Spigate Code 

            //List<AirlineViewModel> allAirlinesViewModel =new List<AirlineViewModel>();

            //var dataFromDB = _applicationDbContext.Airlines.OrderByDescending(a => a).ToList(); 
            //foreach (var item in dataFromDB)
            //{

            //    allAirlinesViewModel.Add(new AirlineViewModel
            //    {
            //        AirlineEmail = item.AirlineEmail,
            //        IATA = item.IATA,
            //        ICAO = item.ICAO,
            //        Id = item.Id,
            //        NameAR = item.NameAR,
            //        NameEN = item.NameEN,
            //        Images = item.Images,
            //        DisplayName = $"{item.IATA} _ {item.NameEN}"
            //    });
            //}




            //  clean  Code

            List  <AirlineViewModel> allData=new List<AirlineViewModel>();
            if (string.IsNullOrEmpty(airlineName))
            {
                allData = _applicationDbContext.Airlines.OrderByDescending(a => a).Select(x => new AirlineViewModel
                {
                    AirlineEmail = x.AirlineEmail,
                    IATA = x.IATA,
                    ICAO = x.ICAO,
                    Id = x.Id,
                    NameAR = x.NameAR,
                    NameEN = x.NameEN,
                    Images = x.Images,
                    DisplayName = $"{x.IATA} _ {x.NameEN}"
                }).ToList();

            }
            else
            {

                airlineName = airlineName.Trim();   

                allData = _applicationDbContext.Airlines.Where(x=>x.NameEN.ToLower().Contains(airlineName) ).OrderByDescending(a => a).Select(x => new AirlineViewModel
                {
                    AirlineEmail = x.AirlineEmail,
                    IATA = x.IATA,
                    ICAO = x.ICAO,
                    Id = x.Id,
                    NameAR = x.NameAR,
                    NameEN = x.NameEN,
                    Images = x.Images,
                    DisplayName = $"{x.IATA} _ {x.NameEN}"
                }).ToList();




            }

            if (User.Identity.IsAuthenticated)
            {
                ViewBag.UserName = User.Identity.Name;
            }
            else
            {
                ViewBag.UserName = "Guest";
            }


            return View(allData);    
        }




        [HttpGet]
        public IActionResult Update(int id)
        {
            if (id == 0)
            {
                ViewBag.ErrMsg = "Value should not be 0";
            }
            var selectedAirline = _applicationDbContext.Airlines.FirstOrDefault(x => x.Id == id);
            return View(selectedAirline);  
        }

        [HttpPost]
        public IActionResult Update(Airline airline)
        {
            var airlineObject = _applicationDbContext.Airlines.FirstOrDefault(x => x.Id == airline.Id);

            if (airlineObject is not null&& ModelState.IsValid)
            { 
                airlineObject.ICAO=airline.ICAO;  
                airlineObject.IATA=airline.IATA;    
                airlineObject.AirlineEmail=airline.AirlineEmail;
                airlineObject.NameEN = airline.NameEN; 
                airlineObject.NameAR = airline.NameAR;  
            }
            return View(airline);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var selectedAirline = _applicationDbContext.Airlines.FirstOrDefault(x => x.Id == id);
            if(selectedAirline is not null)
            _applicationDbContext.Airlines.Remove(selectedAirline);
            _applicationDbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }


    }
}

FlightSchedule/Views/Airline/CreateAirline.cshtml
@model FlightSchedule.Models.AirlineViewModel

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<h4>Airline</h4>


<h6>@ViewBag.ErrMsg</h6>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateAirline"enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Images" class="control-label"></label>
                <div class="custom-file">
                    <input type="file" name="file" class="custom-file-input" id="customFile" accept=".jpg,.jpeg,.png" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="NameEN" class="control-label"></label>
                <input asp-for="NameEN" class="form-control" />
                <span asp-validation-for="NameEN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NameAR" class="control-label"></label>
                <input asp-for="NameAR" class="form-control" />
                <span asp-validation-for="NameAR" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IATA" class="control-label"></label>
                <input asp-for="IATA" class="form-control" />
                <span asp-validation-for="IATA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ICAO" class="control-label"></label>
                <input asp-for="ICAO" class="form-control" />
                <span asp-validation-for="ICAO" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="AirlineEmail" class="control-label"></label>
                <input asp-for="AirlineEmail" class="form-control" />
                <span asp-validation-for="AirlineEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FlightSchedule/Views/Airline/Delete.cshtml
@model FlightSchedule.Enities.Airline

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Airline</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameEN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameEN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameAR)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameAR)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IATA)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IATA)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ICAO)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ICAO)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayFor(model => model.ICAO)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayNameFor(model => model.AirlineEmail)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FlightSchedule/Views/Airline/Index.cshtml
@model IEnumerable<FlightSchedule.Models.AirlineViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-controller="Airline" asp-action="CreateAirline">Create New</a>
</p>




<input type="text" name="searchBox" id="searchBox_id" onblur="searchFunction()" />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NameEN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NameAR)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IATA)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ICAO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AirlineEmail)
            </th>
            <th>Display Name</th>
            <th>Logo</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NameEN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NameAR)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IATA)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ICAO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AirlineEmail)
            </td>
            <td>
                @item.DisplayName
            </td>
             <td>
                    <img src='/images/@item.Images' height="40" width="40" id="image" asp-append-version="true">
             </td>
            <td>
                @Html.ActionLink("Edit", "Update", new { id=item.Id }) |
                <button class="btn btn-danger" onclick="Delete('@item.Id')">Delete</button>
            </td>
        </tr>
}
    </tbody>
</table>


@section Scripts {
   <script>
    
       function Delete(Id){
         if (confirm("Are sure wants to delete?") == true) {
           window.location.href = '/Airline/Delete/'+Id;
           } else {
           window.location.href = '/Airline/Index';
           }

     }

        function searchFunction() {
         var searchValue = document.getElementById("searchBox_id").value;
            if (searchValue) {
                   window.location.href = '/Airline/Index?airlineName=' + encodeURIComponent(searchValue);
         }
         else {
                      window.location.href = '/Airline/Index?airlineName=';
            }
        }   
   </script>
}

FlightSchedule/Views/Airline/Update.cshtml
@model FlightSchedule.Enities.Airline

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>Airline</h4>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @{
                if (Model == null)
                {
                    <h6>@ViewBag.ErrMsg</h6>
                }
                else
                {
                    <div class="form-group">
                        <label asp-for="NameEN" class="control-label"></label>
                        <input asp-for="NameEN" class="form-control" />
                        <span asp-validation-for="NameEN" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="NameAR" class="control-label"></label>
                        <input asp-for="NameAR" class="form-control" />
                        <span asp-validation-for="NameAR" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="IATA" class="control-label"></label>
                        <input asp-for="IATA" class="form-control" />
                        <span asp-validation-for="IATA" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ICAO" class="control-label"></label>
                        <input asp-for="ICAO" class="form-control" />
                        <span asp-validation-for="ICAO" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="AirlineEmail" class="control-label"></label>
                        <input asp-for="AirlineEmail" class="form-control" />
                        <span asp-validation-for="AirlineEmail" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                }
            }

                   
   
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}